# Project:       Foocator (Function obfuscator component)
# Description:   Obfuscates functions to hide IAT.

# CC path: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.30.30705\bin\Hostx64\x64\cl.exe
CC="/mnt/c/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.30.30705/bin/Hostx64/x64/cl.exe"
OUTPUT_FOLDER="./bin"
SOURCE_MAIN="./src/main.cpp"
CC_OPTIONS=

foocator:
	$(CC) $(CC_OPTIONS)